### ISSUE TITLE
BUG: Epi pens not being consumed on stablise or revive

### ISSUE THREAD

**Issue by ferdinandwinters** [willithappen/eams#20]
I stepped in as section medic tonight and noticed that I still had 20 epi at the end of the night. I just checked my load-out and I only had 20 in my inventory so they definitely weren't used.

**PTE(P) Pants**

**Comment by Chrisone4** [comment]
Can confirm. Unknown if it takes Epi's out of patient first.

**Comment by willithappen** [comment]
https://github.com/willithappen/eams/blob/master/functions/revive/fn_reviveComplete.sqf#L15

https://github.com/willithappen/eams/blob/master/functions/revive/fn_stabilizeComplete.sqf#L15

Param was incorrect.

Fixed in https://github.com/willithappen/eams/commit/be97edaa22a07329e2670b5a88e67b1b503d3159
